name: cdc_project
services:
  app:
    image: django-docker:latest
    container_name: cdc_project
    environment:
      - PROJECT_NAME=cdc_project
      - PIPELINE=development
      - SECRET_KEY=.
      - DB_NAME=.
      - DB_USER_NM=.
      - DB_USER_PW=.
      - DB_IP=.
      - DB_PORT=.
      - EMAIL_HOST=.
      - EMAIL_PORT=.
      - EMAIL_HOST_USER=.
      - EMAIL_HOST_PASSWORD=.
    ports:
      - "8080:8000"
    volumes:
      - /home/addohm/cdc_project:/project