# Generated by Django 5.1.5 on 2025-01-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_staff_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselImages',
            new_name='CarouselImage',
        ),
    ]
