# Generated by Django 5.1.5 on 2025-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_divesite_product_staff_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
