# Generated by Django 5.1.5 on 2025-01-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_divesite_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divesite',
            old_name='location',
            new_name='citystateprov',
        ),
    ]
