# Generated by Django 5.1.5 on 2025-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='when_replied',
            field=models.DateTimeField(blank=True),
        ),
    ]
