# Generated by Django 5.1.5 on 2025-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_contact_replied_alter_contact_when_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='when_replied',
            field=models.DateTimeField(null=True),
        ),
    ]
